// Generated by CoffeeScript 1.3.3
(function() {
  var exports, greeter;

  exports = module.exports;

  greeter = require("../models/greeter");

  exports.sayHello = function(req, res) {
    var context, name, template;
    name = req.param("name", "");
    context = {
      site_title: "Node.js Bootstrap Demo Page",
      welcome_message: greeter.welcomeMessage(name)
    };
    template = "../lib/hello/views/hello";
    return res.render(template, context);
  };

}).call(this);
